/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diegocasco_felixdominguez_lab9;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author dcasc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    int centi;
    DefaultComboBoxModel<String> comboboxA=new DefaultComboBoxModel ();
    DefaultComboBoxModel<String> comboboxM=new DefaultComboBoxModel ();
    DefaultComboBoxModel<String> comboboxC=new DefaultComboBoxModel ();
    DefaultComboBoxModel<String> comboboxE=new DefaultComboBoxModel ();
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        for(int i=0;i<alumnos.size();i++){
            String id=String.valueOf(alumnos.get(i).getNombre());
            comboboxA.addElement(id);
        }
        
        for(int i=0;i<maestros.size();i++){
            String id=String.valueOf(maestros.get(i).getNombre());
            comboboxM.addElement(id);
        }
        clases.add(new Clase("Mate"));
        
        for(int i=0;i<clases.size();i++){
            String id=String.valueOf(clases.get(i).getNombre());
            comboboxC.addElement(id);
        }
        for(int i=0;i<examenes.size();i++){
            String id=String.valueOf(examenes.get(i).getIDExamen());
            comboboxC.addElement(id);
        }
        
        //Admin.setVisible(true);
        //Admin.pack();
        CargarAlumno();
        CargarMaestro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin = new javax.swing.JFrame();
        AdminCA = new javax.swing.JButton();
        AdminCM = new javax.swing.JButton();
        AdminEA = new javax.swing.JButton();
        AdminEM = new javax.swing.JButton();
        AdminLA = new javax.swing.JButton();
        AdminLM = new javax.swing.JButton();
        AdminELA = new javax.swing.JButton();
        AdminELM = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CrearExamen = new javax.swing.JButton();
        CrearClase = new javax.swing.JButton();
        CrearPregunta = new javax.swing.JButton();
        VerClase = new javax.swing.JButton();
        VerCalificaciones = new javax.swing.JButton();
        Registro = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        JT_Nombre = new javax.swing.JTextField();
        JT_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JT_contrasena = new javax.swing.JTextField();
        JT_ConfirarContrasena = new javax.swing.JTextField();
        JB_registar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AlumnoCRUD = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreAlumno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CuentaAlumno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ConfirmarAlumno = new javax.swing.JButton();
        CarreraAlumno = new javax.swing.JTextField();
        MaestroCRUD = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NombreMaestro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RRHHMaestro = new javax.swing.JTextField();
        ConfirmarMaestro = new javax.swing.JButton();
        ElegirCombobox = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        ComboboxElegir = new javax.swing.JComboBox<>();
        ConfirmarElegir = new javax.swing.JButton();
        ExamenCrear = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NumPreguntas = new javax.swing.JSpinner();
        ECBoton = new javax.swing.JButton();
        ClaseCombobox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        IDExamen = new javax.swing.JTextField();
        PreguntaCrear = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PreguntaTexto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Verdadero = new javax.swing.JCheckBox();
        Falso = new javax.swing.JCheckBox();
        BotonCP = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        ExamenPregunta = new javax.swing.JComboBox<>();
        Alumno = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        HacerExamen = new javax.swing.JButton();
        PruebaHacer = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        PreguntaPrueba = new javax.swing.JLabel();
        VerdaderoPrueba = new javax.swing.JCheckBox();
        FalsoPrueba = new javax.swing.JCheckBox();
        ConfirmarPrueba = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        NombreCuenta = new javax.swing.JTextField();
        RegistrarBoton = new javax.swing.JButton();
        IniciarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        AdminCA.setText("Crear Alumno");
        AdminCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminCAActionPerformed(evt);
            }
        });

        AdminCM.setText("Crear Maestro");
        AdminCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminCMActionPerformed(evt);
            }
        });

        AdminEA.setText("Editar Alumno");
        AdminEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminEAActionPerformed(evt);
            }
        });

        AdminEM.setText("Editar Maestro");
        AdminEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminEMActionPerformed(evt);
            }
        });

        AdminLA.setText("Listar Alumnos");
        AdminLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLAActionPerformed(evt);
            }
        });

        AdminLM.setText("Listar Maestros");
        AdminLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLMActionPerformed(evt);
            }
        });

        AdminELA.setText("Eliminar Alumno");
        AdminELA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminELAActionPerformed(evt);
            }
        });

        AdminELM.setText("Eliminar Maestro");
        AdminELM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminELMActionPerformed(evt);
            }
        });

        jLabel6.setText("Opciones de Administrador: ");

        CrearExamen.setText("Crear Examen");
        CrearExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearExamenActionPerformed(evt);
            }
        });

        CrearClase.setText("Crear Clase");
        CrearClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClaseActionPerformed(evt);
            }
        });

        CrearPregunta.setText("Crear Pregunta");
        CrearPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPreguntaActionPerformed(evt);
            }
        });

        VerClase.setText("Ver Clases");
        VerClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerClaseActionPerformed(evt);
            }
        });

        VerCalificaciones.setText("Ver Calificaciones");
        VerCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCalificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin.getContentPane());
        Admin.getContentPane().setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(AdminELA)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdminEA)
                                        .addComponent(AdminCA))
                                    .addGap(46, 46, 46))
                                .addGroup(AdminLayout.createSequentialGroup()
                                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdminLA)
                                        .addComponent(CrearExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(44, 44, 44)))
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(VerCalificaciones)
                                .addGap(28, 28, 28))
                            .addComponent(CrearClase))
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VerClase)
                            .addComponent(AdminLM)
                            .addComponent(AdminELM)
                            .addComponent(AdminCM, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminEM)
                            .addComponent(CrearPregunta))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(CrearPregunta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VerCalificaciones)
                        .addGap(26, 26, 26)
                        .addComponent(CrearExamen)))
                .addGap(29, 29, 29)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearClase)
                    .addComponent(VerClase))
                .addGap(27, 27, 27)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminCA)
                    .addComponent(AdminCM))
                .addGap(28, 28, 28)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminEA)
                    .addComponent(AdminEM))
                .addGap(29, 29, 29)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminLA)
                    .addComponent(AdminLM))
                .addGap(31, 31, 31)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminELA)
                    .addComponent(AdminELM))
                .addGap(31, 31, 31))
        );

        JT_Nombre.setText("jTextField2");

        JT_usuario.setText("jTextField3");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        JT_contrasena.setText("jTextField4");

        JT_ConfirarContrasena.setText("jTextField5");

        JB_registar.setText("jButton4");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(JB_registar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_ConfirarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JT_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(JT_Nombre)
                                .addComponent(JT_contrasena))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_ConfirarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(JB_registar)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Alumno");

        jLabel8.setText("Ingrese el nombre:");

        jLabel9.setText("Ingrese el numero de cuenta:");

        jLabel10.setText("Seleccione Carrera:");

        ConfirmarAlumno.setText("Confirmar");
        ConfirmarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlumnoCRUDLayout = new javax.swing.GroupLayout(AlumnoCRUD.getContentPane());
        AlumnoCRUD.getContentPane().setLayout(AlumnoCRUDLayout);
        AlumnoCRUDLayout.setHorizontalGroup(
            AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoCRUDLayout.createSequentialGroup()
                .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlumnoCRUDLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7))
                    .addGroup(AlumnoCRUDLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AlumnoCRUDLayout.createSequentialGroup()
                                .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(CuentaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(CarreraAlumno))))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlumnoCRUDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConfirmarAlumno)
                .addGap(155, 155, 155))
        );
        AlumnoCRUDLayout.setVerticalGroup(
            AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoCRUDLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlumnoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarreraAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(ConfirmarAlumno)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Maestro");

        jLabel12.setText("Ingrese el nombre:");

        jLabel13.setText("Ingrese numero de RRHH");

        ConfirmarMaestro.setText("Confirmar");
        ConfirmarMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarMaestroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaestroCRUDLayout = new javax.swing.GroupLayout(MaestroCRUD.getContentPane());
        MaestroCRUD.getContentPane().setLayout(MaestroCRUDLayout);
        MaestroCRUDLayout.setHorizontalGroup(
            MaestroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestroCRUDLayout.createSequentialGroup()
                .addGroup(MaestroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaestroCRUDLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel11))
                    .addGroup(MaestroCRUDLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(MaestroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(MaestroCRUDLayout.createSequentialGroup()
                                .addComponent(RRHHMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ConfirmarMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        MaestroCRUDLayout.setVerticalGroup(
            MaestroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestroCRUDLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaestroCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRHHMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmarMaestro))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel14.setText("Seleccione:");

        ConfirmarElegir.setText("Confirmar");
        ConfirmarElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ElegirComboboxLayout = new javax.swing.GroupLayout(ElegirCombobox.getContentPane());
        ElegirCombobox.getContentPane().setLayout(ElegirComboboxLayout);
        ElegirComboboxLayout.setHorizontalGroup(
            ElegirComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ElegirComboboxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(93, 93, 93))
            .addGroup(ElegirComboboxLayout.createSequentialGroup()
                .addGroup(ElegirComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ElegirComboboxLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ComboboxElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ElegirComboboxLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(ConfirmarElegir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ElegirComboboxLayout.setVerticalGroup(
            ElegirComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElegirComboboxLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboboxElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ConfirmarElegir)
                .addGap(27, 27, 27))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Crear Examen:");

        jLabel18.setText("IDClase");

        jLabel19.setText("Numero de Preguntas:");

        NumPreguntas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ECBoton.setText("Crear");
        ECBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECBotonActionPerformed(evt);
            }
        });

        jLabel24.setText("IDExamen");

        javax.swing.GroupLayout ExamenCrearLayout = new javax.swing.GroupLayout(ExamenCrear.getContentPane());
        ExamenCrear.getContentPane().setLayout(ExamenCrearLayout);
        ExamenCrearLayout.setHorizontalGroup(
            ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenCrearLayout.createSequentialGroup()
                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExamenCrearLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel17))
                    .addGroup(ExamenCrearLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(ExamenCrearLayout.createSequentialGroup()
                                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NumPreguntas)
                                    .addComponent(jLabel24)
                                    .addComponent(IDExamen, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ClaseCombobox, 0, 111, Short.MAX_VALUE)
                                        .addComponent(ECBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ExamenCrearLayout.setVerticalGroup(
            ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenCrearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExamenCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECBoton))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Crear Pegunta:");

        jLabel21.setText("Pregunta:");

        jLabel22.setText("Respuesta:");

        Verdadero.setText("Verdadero");

        Falso.setText("Falso");

        BotonCP.setText("Crear");
        BotonCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCPActionPerformed(evt);
            }
        });

        jLabel23.setText("Examen:");

        javax.swing.GroupLayout PreguntaCrearLayout = new javax.swing.GroupLayout(PreguntaCrear.getContentPane());
        PreguntaCrear.getContentPane().setLayout(PreguntaCrearLayout);
        PreguntaCrearLayout.setHorizontalGroup(
            PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreguntaCrearLayout.createSequentialGroup()
                .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PreguntaCrearLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel20))
                    .addGroup(PreguntaCrearLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PreguntaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PreguntaCrearLayout.createSequentialGroup()
                                    .addComponent(Verdadero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotonCP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Falso)))
                                .addGroup(PreguntaCrearLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(128, 128, 128)
                                    .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(ExamenPregunta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PreguntaCrearLayout.setVerticalGroup(
            PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreguntaCrearLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreguntaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(1, 1, 1)
                .addGroup(PreguntaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verdadero)
                    .addComponent(Falso)
                    .addComponent(ExamenPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(BotonCP)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Alumno");

        HacerExamen.setText("Examen");
        HacerExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HacerExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlumnoLayout = new javax.swing.GroupLayout(Alumno.getContentPane());
        Alumno.getContentPane().setLayout(AlumnoLayout);
        AlumnoLayout.setHorizontalGroup(
            AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoLayout.createSequentialGroup()
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlumnoLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel25))
                    .addGroup(AlumnoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(HacerExamen)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        AlumnoLayout.setVerticalGroup(
            AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(HacerExamen)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel26.setText("Pregunta: ");

        PreguntaPrueba.setText(" ");

        VerdaderoPrueba.setText("Verdadero");

        FalsoPrueba.setText("Falso");

        ConfirmarPrueba.setText("Confirmar");

        javax.swing.GroupLayout PruebaHacerLayout = new javax.swing.GroupLayout(PruebaHacer.getContentPane());
        PruebaHacer.getContentPane().setLayout(PruebaHacerLayout);
        PruebaHacerLayout.setHorizontalGroup(
            PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PruebaHacerLayout.createSequentialGroup()
                .addGroup(PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PruebaHacerLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(VerdaderoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(FalsoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PruebaHacerLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(ConfirmarPrueba))
                    .addGroup(PruebaHacerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PruebaHacerLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PreguntaPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PruebaHacerLayout.setVerticalGroup(
            PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PruebaHacerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(PreguntaPrueba))
                .addGap(27, 27, 27)
                .addGroup(PruebaHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerdaderoPrueba)
                    .addComponent(FalsoPrueba))
                .addGap(26, 26, 26)
                .addComponent(ConfirmarPrueba)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrarBoton.setText("Registrar");
        RegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotonActionPerformed(evt);
            }
        });

        IniciarBoton.setText("Iniciar");
        IniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Iniciar Sesion");

        jLabel15.setText("Nombre de Cuenta:");

        jLabel16.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IniciarBoton)
                .addGap(75, 75, 75)
                .addComponent(RegistrarBoton)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarBoton)
                    .addComponent(IniciarBoton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCAActionPerformed
        // TODO add your handling code here:
        refresh();
        AlumnoCRUD.setVisible(rootPaneCheckingEnabled);
        AlumnoCRUD.pack();
        centi=1;
    }//GEN-LAST:event_AdminCAActionPerformed

    private void AdminCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCMActionPerformed
        // TODO add your handling code here:
        refresh();
        MaestroCRUD.setVisible(rootPaneCheckingEnabled);
        MaestroCRUD.pack();
        centi=2;
    }//GEN-LAST:event_AdminCMActionPerformed

    private void AdminEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEAActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxA);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=3;
    }//GEN-LAST:event_AdminEAActionPerformed

    private void AdminEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEMActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxM);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=4;
    }//GEN-LAST:event_AdminEMActionPerformed

    private void AdminLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLAActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxA);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=5;
    }//GEN-LAST:event_AdminLAActionPerformed

    private void AdminLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLMActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxM);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=6;
    }//GEN-LAST:event_AdminLMActionPerformed

    private void AdminELAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminELAActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxA);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=7;
    }//GEN-LAST:event_AdminELAActionPerformed

    private void AdminELMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminELMActionPerformed
        // TODO add your handling code here:
        refresh();
        ComboboxElegir.setModel(comboboxM);
        ElegirCombobox.setVisible(rootPaneCheckingEnabled);
        ElegirCombobox.pack();
        centi=8;
    }//GEN-LAST:event_AdminELMActionPerformed

    private void ConfirmarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAlumnoActionPerformed
        // TODO add your handling code here:
        if(centi==1){
            int cuenta=Integer.parseInt(CuentaAlumno.getText());
            alumnos.add(new Alumno(NombreAlumno.getText(),cuenta,CarreraAlumno.getText()));
            AgregarAlumno(alumnos.size()-1);
        }else if(centi==3){
            alumnos.get(ComboboxElegir.getSelectedIndex()).setNombre(NombreAlumno.getText());
            alumnos.get(ComboboxElegir.getSelectedIndex()).setCarrera(CarreraAlumno.getText());
            int cuenta=Integer.parseInt(CuentaAlumno.getText());
            alumnos.get(ComboboxElegir.getSelectedIndex()).setNumerocuenta(cuenta);
            EditarAlumno();
        }
        
    }//GEN-LAST:event_ConfirmarAlumnoActionPerformed

    private void ConfirmarMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarMaestroActionPerformed
        // TODO add your handling code here:
        if(centi==2){
            int RRHH=Integer.parseInt(RRHHMaestro.getText());
            maestros.add(new Maestro(NombreMaestro.getText(),RRHH));
            AgregarMaestro(maestros.size()-1);
        }else if(centi==4){
            String nombre=maestros.get(ComboboxElegir.getSelectedIndex()).getNombre();
            int RRHH=maestros.get(ComboboxElegir.getSelectedIndex()).getNumeroRRHH();
            maestros.get(ComboboxElegir.getSelectedIndex()).setNombre(NombreMaestro.getText());
            int cuenta=Integer.parseInt(RRHHMaestro.getText());
            maestros.get(ComboboxElegir.getSelectedIndex()).setNumeroRRHH(cuenta);
            EditarMaestro(nombre,RRHH);
        }
        
    }//GEN-LAST:event_ConfirmarMaestroActionPerformed

    private void ConfirmarElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarElegirActionPerformed
        // TODO add your handling code here:
        switch (centi) {
            case 3:{
                NombreAlumno.setText(alumnos.get(ComboboxElegir.getSelectedIndex()).getNombre());
                CarreraAlumno.setText(alumnos.get(ComboboxElegir.getSelectedIndex()).getCarrera());
                String cuenta=String.valueOf(alumnos.get(ComboboxElegir.getSelectedIndex()).getNumerocuenta());
                CuentaAlumno.setText(cuenta);
                AlumnoCRUD.setVisible(rootPaneCheckingEnabled);
                AlumnoCRUD.pack();
                centi=3;
                break;
            }
            case 4:{
                NombreMaestro.setText(maestros.get(ComboboxElegir.getSelectedIndex()).getNombre());
                MaestroCRUD.setVisible(rootPaneCheckingEnabled);
                String cuenta=String.valueOf(alumnos.get(ComboboxElegir.getSelectedIndex()).getNumerocuenta());
                CuentaAlumno.setText(cuenta);
                MaestroCRUD.pack();
                centi=4;
                break;
            }
            case 5:{
                JOptionPane.showMessageDialog(null, alumnos.get(ComboboxElegir.getSelectedIndex()));
                
                break;
            }
            case 6:{
                JOptionPane.showMessageDialog(null, maestros.get(ComboboxElegir.getSelectedIndex()));
                
                break;
            }    
            case 7:{
                EliminarAlumno();
                alumnos.remove(ComboboxElegir.getSelectedIndex());
                break;
            }    
            case 8:{
                EliminarMaestro();
                maestros.remove(ComboboxElegir.getSelectedIndex());
                break;
            }    
            
        }
        refresh();
    }//GEN-LAST:event_ConfirmarElegirActionPerformed

    private void IniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarBotonActionPerformed
        // TODO add your handling code here:
        if(NombreCuenta.getText().equals("Admin")&Contraseña.getText().equals("1234")){
            Admin.setVisible(true);
            Admin.pack();
        }else if(NombreCuenta.getText().equals("Maestro")&Contraseña.getText().equals("1111")){
            
        }else if(NombreCuenta.getText().equals("Alumno")&Contraseña.getText().equals("0000")){
            Alumno.setVisible(true);
            Alumno.pack();
        }
    }//GEN-LAST:event_IniciarBotonActionPerformed

    private void RegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotonActionPerformed
        // TODO add your handling code here:
        Registro.setVisible(true);
        Registro.pack();
    }//GEN-LAST:event_RegistrarBotonActionPerformed

    private void VerCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerCalificacionesActionPerformed

    private void CrearPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPreguntaActionPerformed
        // TODO add your handling code here:
        refresh();
        ExamenPregunta.setModel(comboboxE);
        PreguntaCrear.setVisible(true);
        PreguntaCrear.pack();
    }//GEN-LAST:event_CrearPreguntaActionPerformed

    private void VerClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerClaseActionPerformed

    private void CrearExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearExamenActionPerformed
        // TODO add your handling code here:
        refresh();
        ClaseCombobox.setModel(comboboxC);
        ExamenCrear.setVisible(true);
        ExamenCrear.pack();
    }//GEN-LAST:event_CrearExamenActionPerformed

    private void CrearClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClaseActionPerformed
        // TODO add your handling code here:
        String clase=JOptionPane.showInputDialog(null, "Ingrese el nombre de la clase:");
        clases.add(new Clase(clase));
    }//GEN-LAST:event_CrearClaseActionPerformed

    private void ECBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECBotonActionPerformed
        // TODO add your handling code here:
        int ad=(Integer) NumPreguntas.getValue();
        examenes.add(new Examen(IDExamen.getText(),ad,clases.get(ClaseCombobox.getSelectedIndex())));
    }//GEN-LAST:event_ECBotonActionPerformed

    private void BotonCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCPActionPerformed
        // TODO add your handling code here:
        if(Verdadero.isSelected()){
            preguntas.add(new Pregunta(PreguntaTexto.getText(),true,examenes.get(ExamenPregunta.getSelectedIndex())));
        }else if(Falso.isSelected()){
            
        }
    }//GEN-LAST:event_BotonCPActionPerformed

    private void HacerExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HacerExamenActionPerformed
        // TODO add your handling code here:
        PruebaHacer.setVisible(true);
        PruebaHacer.pack();
        PreguntaPrueba.setText(preguntas.get(0).getPregunta());
    }//GEN-LAST:event_HacerExamenActionPerformed

    public void refresh(){
        comboboxM.removeAllElements();
        comboboxA.removeAllElements();
        comboboxE.removeAllElements();
        comboboxC.removeAllElements();
        
        for(int i=0;i<maestros.size();i++){
            comboboxM.addElement(maestros.get(i).getNombre());
        }
        for(int i=0;i<alumnos.size();i++){
            comboboxA.addElement(alumnos.get(i).getNombre());
        }   
        for(int i=0;i<examenes.size();i++){
            comboboxE.addElement(examenes.get(i).getIDExamen());
        }
        for(int i=0;i<clases.size();i++){
            comboboxC.addElement(clases.get(i).getNombre());
        }
    }
    
    public void AgregarAlumno(int e){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("INSERT INTO Alumno"
                    + " (Nombre,Cuenta,Carrera)"
                    + " VALUES ('" + alumnos.get(e).getNombre() + "', '" + alumnos.get(e).getNumerocuenta() + "', '" + alumnos.get(e).getCarrera() + "')");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }
    
    public void AgregarMaestro(int e){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("INSERT INTO Maestro"
                    + " (Nombre,RRHH)"
                    + " VALUES ('" + maestros.get(e).getNombre() + "', '" + maestros.get(e).getNumeroRRHH() + "')");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }
    
    public void CargarAlumno(){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("select Nombre,Cuenta,Carrera from Alumno");
            ResultSet rs = db.query.getResultSet();           
            while (rs.next()) {
                alumnos.add(new Alumno(rs.getString(1),rs.getInt(2),rs.getString(3)));
            }            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }
    
    public void CargarMaestro(){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("select Nombre,RRHH from Maestro");
            ResultSet rs = db.query.getResultSet();           
            while (rs.next()) {
                maestros.add(new Maestro(rs.getString(1),rs.getInt(2)));
            }            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }
    
    public void EliminarMaestro(){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("delete from Maestro where RRHH="+maestros.get(ComboboxElegir.getSelectedIndex()).getNumeroRRHH());        
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }
    
    public void EliminarAlumno(){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("delete from Alumno where Cuenta="+alumnos.get(ComboboxElegir.getSelectedIndex()).getNumerocuenta());        
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }
    
     public void EditarAlumno(){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("update Alumno set Nombre="+alumnos.get(ComboboxElegir.getSelectedIndex()).getNombre());
            db.query.execute("update Alumno set Cuenta="+alumnos.get(ComboboxElegir.getSelectedIndex()).getNumerocuenta());  
            db.query.execute("update Alumno set Carrera="+alumnos.get(ComboboxElegir.getSelectedIndex()).getCarrera());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }
     
      public void EditarMaestro(String nombre,int RRHH){
        Dba db = new Dba("./Lab9BaseDatos.accdb");
        db.conectar();
        try {
            db.query.execute("update Maestro set Nombre="+nombre+" where Nombre="+maestros.get(ComboboxElegir.getSelectedIndex()).getNombre());
            db.query.execute("update Maestro set RRHH="+RRHH+" where RRHH="+maestros.get(ComboboxElegir.getSelectedIndex()).getNumeroRRHH());        
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Admin;
    private javax.swing.JButton AdminCA;
    private javax.swing.JButton AdminCM;
    private javax.swing.JButton AdminEA;
    private javax.swing.JButton AdminELA;
    private javax.swing.JButton AdminELM;
    private javax.swing.JButton AdminEM;
    private javax.swing.JButton AdminLA;
    private javax.swing.JButton AdminLM;
    private javax.swing.JFrame Alumno;
    private javax.swing.JDialog AlumnoCRUD;
    private javax.swing.JButton BotonCP;
    private javax.swing.JTextField CarreraAlumno;
    private javax.swing.JComboBox<String> ClaseCombobox;
    private javax.swing.JComboBox<String> ComboboxElegir;
    private javax.swing.JButton ConfirmarAlumno;
    private javax.swing.JButton ConfirmarElegir;
    private javax.swing.JButton ConfirmarMaestro;
    private javax.swing.JButton ConfirmarPrueba;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JButton CrearClase;
    private javax.swing.JButton CrearExamen;
    private javax.swing.JButton CrearPregunta;
    private javax.swing.JTextField CuentaAlumno;
    private javax.swing.JButton ECBoton;
    private javax.swing.JDialog ElegirCombobox;
    private javax.swing.JDialog ExamenCrear;
    private javax.swing.JComboBox<String> ExamenPregunta;
    private javax.swing.JCheckBox Falso;
    private javax.swing.JCheckBox FalsoPrueba;
    private javax.swing.JButton HacerExamen;
    private javax.swing.JTextField IDExamen;
    private javax.swing.JButton IniciarBoton;
    private javax.swing.JButton JB_registar;
    private javax.swing.JTextField JT_ConfirarContrasena;
    private javax.swing.JTextField JT_Nombre;
    private javax.swing.JTextField JT_contrasena;
    private javax.swing.JTextField JT_usuario;
    private javax.swing.JDialog MaestroCRUD;
    private javax.swing.JTextField NombreAlumno;
    private javax.swing.JTextField NombreCuenta;
    private javax.swing.JTextField NombreMaestro;
    private javax.swing.JSpinner NumPreguntas;
    private javax.swing.JDialog PreguntaCrear;
    private javax.swing.JLabel PreguntaPrueba;
    private javax.swing.JTextField PreguntaTexto;
    private javax.swing.JDialog PruebaHacer;
    private javax.swing.JTextField RRHHMaestro;
    private javax.swing.JButton RegistrarBoton;
    private javax.swing.JFrame Registro;
    private javax.swing.JButton VerCalificaciones;
    private javax.swing.JButton VerClase;
    private javax.swing.JCheckBox Verdadero;
    private javax.swing.JCheckBox VerdaderoPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuarios> usuarios= new ArrayList();
    ArrayList<Alumno> alumnos= new ArrayList();
    ArrayList<Maestro> maestros= new ArrayList();
    ArrayList<Examen> examenes= new ArrayList();
    ArrayList<Pregunta> preguntas=new ArrayList();
    ArrayList<Clase> clases=new ArrayList();
}
